/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  color: {
    base: {
      white: {
        key: "{color.base.white}",
        $value: "#ffffff",
        $type: "color",
        filePath: "design-tokens/0-atomic/color.json",
        isSource: true,
        original: {
          $value: "#ffffff",
          $type: "color",
          key: "{color.base.white}",
        },
        name: "ColorBaseWhite",
        attributes: {
          category: "color",
          type: "base",
          item: "white",
        },
        path: ["color", "base", "white"],
      },
      black: {
        key: "{color.base.black}",
        $value: "#000000",
        $type: "color",
        filePath: "design-tokens/0-atomic/color.json",
        isSource: true,
        original: {
          $value: "#000000",
          $type: "color",
          key: "{color.base.black}",
        },
        name: "ColorBaseBlack",
        attributes: {
          category: "color",
          type: "base",
          item: "black",
        },
        path: ["color", "base", "black"],
      },
      gray: {
        50: {
          key: "{color.base.gray.50}",
          $value: "#f9fafb",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#f9fafb",
            $type: "color",
            key: "{color.base.gray.50}",
          },
          name: "ColorBaseGray50",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "50",
          },
          path: ["color", "base", "gray", "50"],
        },
        100: {
          key: "{color.base.gray.100}",
          $value: "#f3f4f6",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#f3f4f6",
            $type: "color",
            key: "{color.base.gray.100}",
          },
          name: "ColorBaseGray100",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "100",
          },
          path: ["color", "base", "gray", "100"],
        },
        200: {
          key: "{color.base.gray.200}",
          $value: "#e5e7eb",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#e5e7eb",
            $type: "color",
            key: "{color.base.gray.200}",
          },
          name: "ColorBaseGray200",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "200",
          },
          path: ["color", "base", "gray", "200"],
        },
        300: {
          key: "{color.base.gray.300}",
          $value: "#d1d5db",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#d1d5db",
            $type: "color",
            key: "{color.base.gray.300}",
          },
          name: "ColorBaseGray300",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "300",
          },
          path: ["color", "base", "gray", "300"],
        },
        400: {
          key: "{color.base.gray.400}",
          $value: "#9ca3af",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#9ca3af",
            $type: "color",
            key: "{color.base.gray.400}",
          },
          name: "ColorBaseGray400",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "400",
          },
          path: ["color", "base", "gray", "400"],
        },
        500: {
          key: "{color.base.gray.500}",
          $value: "#6b7280",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#6b7280",
            $type: "color",
            key: "{color.base.gray.500}",
          },
          name: "ColorBaseGray500",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "500",
          },
          path: ["color", "base", "gray", "500"],
        },
        600: {
          key: "{color.base.gray.600}",
          $value: "#4b5563",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#4b5563",
            $type: "color",
            key: "{color.base.gray.600}",
          },
          name: "ColorBaseGray600",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "600",
          },
          path: ["color", "base", "gray", "600"],
        },
        700: {
          key: "{color.base.gray.700}",
          $value: "#374151",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#374151",
            $type: "color",
            key: "{color.base.gray.700}",
          },
          name: "ColorBaseGray700",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "700",
          },
          path: ["color", "base", "gray", "700"],
        },
        800: {
          key: "{color.base.gray.800}",
          $value: "#1f2937",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#1f2937",
            $type: "color",
            key: "{color.base.gray.800}",
          },
          name: "ColorBaseGray800",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "800",
          },
          path: ["color", "base", "gray", "800"],
        },
        900: {
          key: "{color.base.gray.900}",
          $value: "#111827",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#111827",
            $type: "color",
            key: "{color.base.gray.900}",
          },
          name: "ColorBaseGray900",
          attributes: {
            category: "color",
            type: "base",
            item: "gray",
            subitem: "900",
          },
          path: ["color", "base", "gray", "900"],
        },
      },
      blue: {
        500: {
          key: "{color.base.blue.500}",
          $value: "#3b82f6",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#3b82f6",
            $type: "color",
            key: "{color.base.blue.500}",
          },
          name: "ColorBaseBlue500",
          attributes: {
            category: "color",
            type: "base",
            item: "blue",
            subitem: "500",
          },
          path: ["color", "base", "blue", "500"],
        },
      },
      red: {
        500: {
          key: "{color.base.red.500}",
          $value: "#ef4444",
          $type: "color",
          filePath: "design-tokens/0-atomic/color.json",
          isSource: true,
          original: {
            $value: "#ef4444",
            $type: "color",
            key: "{color.base.red.500}",
          },
          name: "ColorBaseRed500",
          attributes: {
            category: "color",
            type: "base",
            item: "red",
            subitem: "500",
          },
          path: ["color", "base", "red", "500"],
        },
      },
    },
  },
  font: {
    family: {
      sans: {
        key: "{font.family.sans}",
        $value: "Inter, sans-serif",
        $type: "fontFamily",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: "Inter, sans-serif",
          $type: "fontFamily",
          key: "{font.family.sans}",
        },
        name: "FontFamilySans",
        attributes: {
          category: "font",
          type: "family",
          item: "sans",
        },
        path: ["font", "family", "sans"],
      },
      mono: {
        key: "{font.family.mono}",
        $value: "monospace",
        $type: "fontFamily",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: "monospace",
          $type: "fontFamily",
          key: "{font.family.mono}",
        },
        name: "FontFamilyMono",
        attributes: {
          category: "font",
          type: "family",
          item: "mono",
        },
        path: ["font", "family", "mono"],
      },
    },
    weight: {
      regular: {
        key: "{font.weight.regular}",
        $value: 400,
        $type: "fontWeight",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: 400,
          $type: "fontWeight",
          key: "{font.weight.regular}",
        },
        name: "FontWeightRegular",
        attributes: {
          category: "font",
          type: "weight",
          item: "regular",
        },
        path: ["font", "weight", "regular"],
      },
      bold: {
        key: "{font.weight.bold}",
        $value: 700,
        $type: "fontWeight",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: 700,
          $type: "fontWeight",
          key: "{font.weight.bold}",
        },
        name: "FontWeightBold",
        attributes: {
          category: "font",
          type: "weight",
          item: "bold",
        },
        path: ["font", "weight", "bold"],
      },
    },
    size: {
      sm: {
        key: "{font.size.sm}",
        $value: "0.875rem",
        $type: "dimension",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: "0.875rem",
          $type: "dimension",
          key: "{font.size.sm}",
        },
        name: "FontSizeSm",
        attributes: {
          category: "font",
          type: "size",
          item: "sm",
        },
        path: ["font", "size", "sm"],
      },
      base: {
        key: "{font.size.base}",
        $value: "1rem",
        $type: "dimension",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: "1rem",
          $type: "dimension",
          key: "{font.size.base}",
        },
        name: "FontSizeBase",
        attributes: {
          category: "font",
          type: "size",
          item: "base",
        },
        path: ["font", "size", "base"],
      },
      lg: {
        key: "{font.size.lg}",
        $value: "1.125rem",
        $type: "dimension",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: "1.125rem",
          $type: "dimension",
          key: "{font.size.lg}",
        },
        name: "FontSizeLg",
        attributes: {
          category: "font",
          type: "size",
          item: "lg",
        },
        path: ["font", "size", "lg"],
      },
      xl: {
        key: "{font.size.xl}",
        $value: "1.25rem",
        $type: "dimension",
        filePath: "design-tokens/0-atomic/typography.json",
        isSource: true,
        original: {
          $value: "1.25rem",
          $type: "dimension",
          key: "{font.size.xl}",
        },
        name: "FontSizeXl",
        attributes: {
          category: "font",
          type: "size",
          item: "xl",
        },
        path: ["font", "size", "xl"],
      },
    },
  },
  semantic: {
    color: {
      primary: {
        key: "{semantic.color.primary}",
        $value: "#3b82f6",
        $type: "color",
        filePath: "design-tokens/1-semantic/color.json",
        isSource: true,
        original: {
          $value: "{color.base.blue.500}",
          $type: "color",
          key: "{semantic.color.primary}",
        },
        name: "SemanticColorPrimary",
        attributes: {
          category: "semantic",
          type: "color",
          item: "primary",
        },
        path: ["semantic", "color", "primary"],
      },
      background: {
        default: {
          key: "{semantic.color.background.default}",
          $value: "#ffffff",
          $type: "color",
          filePath: "design-tokens/1-semantic/color.json",
          isSource: true,
          original: {
            $value: "{color.base.white}",
            $type: "color",
            key: "{semantic.color.background.default}",
          },
          name: "SemanticColorBackgroundDefault",
          attributes: {
            category: "semantic",
            type: "color",
            item: "background",
            subitem: "default",
          },
          path: ["semantic", "color", "background", "default"],
        },
        dark: {
          key: "{semantic.color.background.dark}",
          $value: "#111827",
          $type: "color",
          filePath: "design-tokens/1-semantic/color.json",
          isSource: true,
          original: {
            $value: "{color.base.gray.900}",
            $type: "color",
            key: "{semantic.color.background.dark}",
          },
          name: "SemanticColorBackgroundDark",
          attributes: {
            category: "semantic",
            type: "color",
            item: "background",
            subitem: "dark",
          },
          path: ["semantic", "color", "background", "dark"],
        },
      },
      text: {
        primary: {
          key: "{semantic.color.text.primary}",
          $value: "#111827",
          $type: "color",
          filePath: "design-tokens/1-semantic/color.json",
          isSource: true,
          original: {
            $value: "{color.base.gray.900}",
            $type: "color",
            key: "{semantic.color.text.primary}",
          },
          name: "SemanticColorTextPrimary",
          attributes: {
            category: "semantic",
            type: "color",
            item: "text",
            subitem: "primary",
          },
          path: ["semantic", "color", "text", "primary"],
        },
        inverse: {
          key: "{semantic.color.text.inverse}",
          $value: "#ffffff",
          $type: "color",
          filePath: "design-tokens/1-semantic/color.json",
          isSource: true,
          original: {
            $value: "{color.base.white}",
            $type: "color",
            key: "{semantic.color.text.inverse}",
          },
          name: "SemanticColorTextInverse",
          attributes: {
            category: "semantic",
            type: "color",
            item: "text",
            subitem: "inverse",
          },
          path: ["semantic", "color", "text", "inverse"],
        },
      },
      status: {
        error: {
          key: "{semantic.color.status.error}",
          $value: "#ef4444",
          $type: "color",
          filePath: "design-tokens/1-semantic/color.json",
          isSource: true,
          original: {
            $value: "{color.base.red.500}",
            $type: "color",
            key: "{semantic.color.status.error}",
          },
          name: "SemanticColorStatusError",
          attributes: {
            category: "semantic",
            type: "color",
            item: "status",
            subitem: "error",
          },
          path: ["semantic", "color", "status", "error"],
        },
      },
    },
  },
  component: {
    button: {
      bg: {
        primary: {
          key: "{component.button.bg.primary}",
          $value: "#3b82f6",
          $type: "color",
          filePath: "design-tokens/2-component/button.json",
          isSource: true,
          original: {
            $value: "{semantic.color.primary}",
            $type: "color",
            key: "{component.button.bg.primary}",
          },
          name: "ComponentButtonBgPrimary",
          attributes: {
            category: "component",
            type: "button",
            item: "bg",
            subitem: "primary",
          },
          path: ["component", "button", "bg", "primary"],
        },
      },
      text: {
        primary: {
          key: "{component.button.text.primary}",
          $value: "#ffffff",
          $type: "color",
          filePath: "design-tokens/2-component/button.json",
          isSource: true,
          original: {
            $value: "{semantic.color.text.inverse}",
            $type: "color",
            key: "{component.button.text.primary}",
          },
          name: "ComponentButtonTextPrimary",
          attributes: {
            category: "component",
            type: "button",
            item: "text",
            subitem: "primary",
          },
          path: ["component", "button", "text", "primary"],
        },
      },
      padding: {
        default: {
          key: "{component.button.padding.default}",
          $value: "0.5rem 1rem",
          $type: "dimension",
          filePath: "design-tokens/2-component/button.json",
          isSource: true,
          original: {
            $value: "0.5rem 1rem",
            $type: "dimension",
            key: "{component.button.padding.default}",
          },
          name: "ComponentButtonPaddingDefault",
          attributes: {
            category: "component",
            type: "button",
            item: "padding",
            subitem: "default",
          },
          path: ["component", "button", "padding", "default"],
        },
      },
    },
  },
  pattern: {
    card: {
      container: {
        bg: {
          key: "{pattern.card.container.bg}",
          $value: "#ffffff",
          $type: "color",
          filePath: "design-tokens/3-pattern/card.json",
          isSource: true,
          original: {
            $value: "{semantic.color.background.default}",
            $type: "color",
            key: "{pattern.card.container.bg}",
          },
          name: "PatternCardContainerBg",
          attributes: {
            category: "pattern",
            type: "card",
            item: "container",
            subitem: "bg",
          },
          path: ["pattern", "card", "container", "bg"],
        },
        radius: {
          key: "{pattern.card.container.radius}",
          $value: "0.5rem",
          $type: "dimension",
          filePath: "design-tokens/3-pattern/card.json",
          isSource: true,
          original: {
            $value: "0.5rem",
            $type: "dimension",
            key: "{pattern.card.container.radius}",
          },
          name: "PatternCardContainerRadius",
          attributes: {
            category: "pattern",
            type: "card",
            item: "container",
            subitem: "radius",
          },
          path: ["pattern", "card", "container", "radius"],
        },
        shadow: {
          key: "{pattern.card.container.shadow}",
          $value: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
          $type: "shadow",
          filePath: "design-tokens/3-pattern/card.json",
          isSource: true,
          original: {
            $value: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
            $type: "shadow",
            key: "{pattern.card.container.shadow}",
          },
          name: "PatternCardContainerShadow",
          attributes: {
            category: "pattern",
            type: "card",
            item: "container",
            subitem: "shadow",
          },
          path: ["pattern", "card", "container", "shadow"],
        },
      },
    },
  },
  context: {
    dark: {
      semantic: {
        color: {
          background: {
            default: {
              key: "{context.dark.semantic.color.background.default}",
              $value: "#111827",
              $type: "color",
              filePath: "design-tokens/4-context/theme-dark.json",
              isSource: true,
              original: {
                $value: "{color.base.gray.900}",
                $type: "color",
                key: "{context.dark.semantic.color.background.default}",
              },
              name: "ContextDarkSemanticColorBackgroundDefault",
              attributes: {
                category: "context",
                type: "dark",
                item: "semantic",
                subitem: "color",
                state: "background",
              },
              path: [
                "context",
                "dark",
                "semantic",
                "color",
                "background",
                "default",
              ],
            },
          },
          text: {
            primary: {
              key: "{context.dark.semantic.color.text.primary}",
              $value: "#ffffff",
              $type: "color",
              filePath: "design-tokens/4-context/theme-dark.json",
              isSource: true,
              original: {
                $value: "{color.base.white}",
                $type: "color",
                key: "{context.dark.semantic.color.text.primary}",
              },
              name: "ContextDarkSemanticColorTextPrimary",
              attributes: {
                category: "context",
                type: "dark",
                item: "semantic",
                subitem: "color",
                state: "text",
              },
              path: ["context", "dark", "semantic", "color", "text", "primary"],
            },
          },
        },
      },
    },
  },
};
